### ISSUE TITLE
Error 404 in /loserbox-confirmation page

### ISSUE THREAD

**Issue by bhavesh92pandey** [n1c01a5/recover-website#110]
<img width="1020" alt="Screenshot 2021-02-12 at 19 56 16" src="https://user-images.githubusercontent.com/72858592/107810082-6434a780-6d6c-11eb-9ddf-0e7ece503ba0.png">

**Comment by n1c01a5** [comment]
I just fixed it:https://github.com/n1c01a5/recover-website/commit/bd71fedaa01b45b506586617cb8f37bd0cc0ed44
Wait for the build and close it if it's fine.
@bhavesh92pandey
