### ISSUE TITLE
Blog 1 and Blog 2 page design - Task 13

### ISSUE THREAD

**Issue by bhavesh92pandey** [n1c01a5/recover-website#29]
- Design the page. Look Figma for the design
- Should include Topic, Title, and resume followed by author name, time to read, and date
- See blog.kleros.io for reference 
- Symmetry, padding and text size, and font should be the same as all the other pages
- Link for Task list https://docs.google.com/spreadsheets/d/1x76BTbLm9dpUixjRy43NlEZJfgvPiMtH6QLg66fAmYA/edit#gid=0
- Link for design (Figma) - https://www.figma.com/file/a4C0WETqHQR4siSgnRNnn1b7/RECOVER?node-id=2002%3A8

**Comment by amitg01** [comment]
@bhavesh92pandey 
1. What image should I use for the cover photo of a single blog?
2. How are we calculating the time to read, should I just put a placeholder for now?

**Comment by bhavesh92pandey** [comment]
Hi @amitg01 

1. I can send you an image which we can use for the cover photo for now.
2. Maybe for the Escrow blog put time as 4 min and for Phone recovery, put it as 6min
3. WIll send you the images now

**Comment by bhavesh92pandey** [comment]
Kindly find attached the photos:

![Bhavesh_Linkedin ](https://user-images.githubusercontent.com/72858592/102324833-a915ab00-3f82-11eb-90a8-36e9d8ef7b90.jpeg)
![Nicolas_Linkedin ](https://user-images.githubusercontent.com/72858592/102324835-a9ae4180-3f82-11eb-8f98-9518b9ea2fba.jpeg)
