### ISSUE TITLE
3. Home page: Responsive Menu bar

### ISSUE THREAD

**Issue by bhavesh92pandey** [n1c01a5/recover-website#91]
— The stopping point of the appeared graphic should be aligned with the three rows of menu

— The cross can be placed a little on the top left, in the corner of the appeared graphic 

<img width="504" alt="Screenshot 2021-02-01 at 19 59 32" src="https://user-images.githubusercontent.com/72858592/106507604-95d78400-64cb-11eb-9fd6-599dfe1e10ee.png">

**Comment by n1c01a5** [comment]
"The stopping point of the appeared graphic should be aligned with the three rows of menu" nop

**Comment by n1c01a5** [comment]
also it's not the good cross
