### ISSUE TITLE
The animation of the menu on the smartphone format is buggy

### ISSUE THREAD

**Issue by n1c01a5** [n1c01a5/recover-website#96]

**Comment by bhavesh92pandey** [comment]
I am attaching the screenshot of PR #30 and PR #85. I think it should be good if we set it like PR #30 
<img width="405" alt="Screenshot 2021-02-03 at 10 52 55" src="https://user-images.githubusercontent.com/72858592/106729879-4483dd80-660e-11eb-88af-677d3a4a8948.png">
<img width="399" alt="Screenshot 2021-02-03 at 10 53 13" src="https://user-images.githubusercontent.com/72858592/106729884-451c7400-660e-11eb-8efd-5fce39ad6312.png">

Let me know what you think @n1c01a5
